/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Father service. Represents a row in the &quot;Father&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.test.model.impl.FatherModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.test.model.impl.FatherImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Father
 * @generated
 */
@ProviderType
public interface FatherModel extends BaseModel<Father> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a father model instance should use the {@link Father} interface instead.
	 */

	/**
	 * Returns the primary key of this father.
	 *
	 * @return the primary key of this father
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this father.
	 *
	 * @param primaryKey the primary key of this father
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the fid of this father.
	 *
	 * @return the fid of this father
	 */
	public long getFid();

	/**
	 * Sets the fid of this father.
	 *
	 * @param fid the fid of this father
	 */
	public void setFid(long fid);

	/**
	 * Returns the fname of this father.
	 *
	 * @return the fname of this father
	 */
	@AutoEscape
	public String getFname();

	/**
	 * Sets the fname of this father.
	 *
	 * @param fname the fname of this father
	 */
	public void setFname(String fname);

	/**
	 * Returns the occupation of this father.
	 *
	 * @return the occupation of this father
	 */
	@AutoEscape
	public String getOccupation();

	/**
	 * Sets the occupation of this father.
	 *
	 * @param occupation the occupation of this father
	 */
	public void setOccupation(String occupation);

	@Override
	public Father cloneWithOriginalValues();

}